language: python
python:
- '3.5'
- '3.6'
- 3.7-dev
- nightly
install:
- pip install poetry codecov
- poetry install
script:
- poetry run pytest -v --cov aionursery --cov-report term-missing test_aionursery.py
- codecov
- .travis/publish.sh
env:
  PYPI_PASSWORD:
    secure: "zCbyvTQV6p4bCQplMOVwiJNpOEtmenrEhALtmn0hA85orGrpQHgbiE5R1efv+ntq2T7Us+9Q817bgL4axhATyqxQxwUX7rJxjrpI5jRNr3VtGQFkYAyF420J2jzehlOvWx3yVtKMi4cBhMo6Hg+bx+gyHhjLXQxCY28+cYDDAqYD/Qmeoaj7mbv4XHEcSRNFBLDTMnxxTy4hPXZflP+mp+p+T7C7+Ud693PkAf5PnO4aEIBtEsgEGGgretSsq8YPVhlHIcHUdXIDDZtCpwCcCn7B8w0eGaHGB5sdIcMqtTucl7NtHkA/Kntfat3P9WOkxY6PwAj6WakVY+FssHaq3O6eKp2ocUiIRfHaBA93A9EQ4iJvAqyOy2ko8t6mjZqMMNqpLHGERs6XPgVDtP5m7bl9oK/Fg9AUGvaMKPMdUjRWawtogtKmFY3wUM7hiAOhMUVxL7jKtKw7htonwTpOzfnIR16w64a8ppq5O3LQn2em2DIstzJjU8wyiliH0cA/MF+AK3T05LWw1k2Q6IBHjIvBjHFHJX6RaUeIjRF90LxqeI5asMe9Vhka+R7ZwDNBHsz8fLc/jnttCixmQppKEmE9Ap1cfwXw+it4g7MpM/EOwlBH6Zh3+KBxC5UfEryLn1498vmJ+CbuAxPvqx25uUpwq9GvU3wAYtR+m0/BJTw="
