language: python
python:
- '3.5'
- '3.6'
- 3.7-dev
- nightly
install:
- pip install poetry codecov
- poetry install
script:
- poetry run pytest -v --cov aionursery --cov-report term-missing test_aionursery.py
- codecov
- .travis/publish.sh
env:
  global:
  - secure: bjbmdn9mj0yzHDjXDshUsUfahyLRMYWGje9rdZVz+hNb0iaS/JPYoGL8nOylBjOd1FYHiPJAF1MC+2V7f0Y6G01qqbDWJLD5xyKXYuiKR+9b9OOFwA8rI/DnS9t3IshNIh1Pmexe3jEQ1Me0lYbbHCgIZ8/kFW88wuOXVyHTDXFUoU2rPwwdIE+Gq/XcLwxbO6D8LTCOoho4VtI/NDe0Nd66kKudp3tiCeTsfk+GYixQGlOwa3jC/t+hqy2PDmaHLmzHVdE7CwQhEaBXclyzJU+Hd+kM6IVETzxOwnKEQwPvut0tn+6Yt4DaGOkX3bD2lZz5vhQxEI+To0M/SEv/eFhys1ipwFPkrNjB20HKYp0FZtWmGwQAKuzeilL6VwAwDvTwfV9Z/K++uPoeDIg+mIz0QR9v4hnx/jOybM45VJY/C5TCdlOPptPhG+WaPZMHJoxZNfJVRnCXr/46r5StE0V8u16UjV4B9HJ1reJyVDVU1fhub/g7An2M2JJ060Y4j/d05YOZRA2csrasqIthAs6A+abYcPpFLIrEo3HOoYPd2b74uT9Y4djSHY3dd3k4pJOo3sYb4ZRa+NzspXdmjn9VruLePG967aPNtBVT40gqImBSD05tVHuZ8tZ32W1pPUUmKXFRtQ2ogNpDkZFKz5Ylrh1Qqfv7ZqvYlqWsN+A=
